//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeoutBeater.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>EMC64</string>
  <string>wfica32</string>
  <string>notepad</string>
  <string>notepad++</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ProcessNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProcessNames"]));
            }
            set {
                this["ProcessNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F3</string>
  <string>F1</string>
  <string>F5</string>
  <string>F5</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ProcessKeyPresses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProcessKeyPresses"]));
            }
            set {
                this["ProcessKeyPresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>false</string>
  <string>false</string>
  <string>true</string>
  <string>true</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ProcessEnabled {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProcessEnabled"]));
            }
            set {
                this["ProcessEnabled"] = value;
            }
        }
    }
}
